### ISSUE TITLE
有没有群组At自己的消息类型呢？

### ISSUE THREAD

**Issue by ZhelinCheng** [YunYouJun/mirai-ts#15]
我现在判断是否at机器人自己的消息我是通过messageChain的At来判断的，是否提供了更简洁的方案呢？
```
{
  type: 'GroupMessage',
  messageChain: [
    { type: 'Source', id: 599, time: 1603352515 },
    { type: 'At', target: 1000009, display: '@测试' }
  ],
  sender: {
    id: 1000003,
    memberName: 'L 、',
    permission: 'OWNER',
    group: { id: 23423424, name: '测试群组', permission: 'MEMBER' }
  },
  plain: '',
  reply: [Function]
}
```

**Comment by YunYouJun** [comment]
判断消息链是否有艾特某人：

```js
const { check } = require("mirai-ts");
check.isAt(qq);
```

**Comment by ZhelinCheng** [comment]
> 判断消息链是否有艾特某人：
> 
> ```js
> const { check } = require("mirai-ts");
> check.isAt(qq);
> ```

谢谢

**Comment by YunYouJun** [comment]
写了个参数……

msg 是消息链。

```js
check.isAt(msg, qq)
```

**Comment by ZhelinCheng** [comment]
> 写漏了个参数……
> 
> msg 是消息链。
> 
> ```js
> check.isAt(msg, qq)
> ```

TS提示了，23333

**Comment by ZhelinCheng** [comment]
我刚刚试了试这个方法，一直返回`false`
```
check.isAt(msg, ctx.mirai.qq)
```
我是如此判断的
@YunYouJun

**Comment by YunYouJun** [comment]
应该是  `ctx.el.qq`，没有 `ctx.mirai.qq`。

**Comment by YunYouJun** [comment]
因为艾特这个操作还是挺常用的。我也在考虑直接为消息链添加一个辅助函数，如 `msg.isAt(qq)`，留空 `msg.isAt()` 则代表是否艾特自己。这样 API 更为简洁。可能会在下个版本加入。

**Comment by ZhelinCheng** [comment]
有点比较尴尬的问题，` ctx.el.qq`的类型是number，实际它是string，所以对比就一直是false

**Comment by ZhelinCheng** [comment]
> 因为艾特这个操作还是挺常用的。我也在考虑直接为消息链添加一个辅助函数，如 `msg.isAt(qq)`，留空 `msg.isAt()` 则代表是否艾特自己。这样 API 更为简洁。可能会在下个版本加入。

之前用酷Q的HTTP时候，at属于群组事件的一个子事件，也挺好用的，很多时候群组里面机器人只会响应at

**Comment by YunYouJun** [comment]
> 有点比较尴尬的问题，` ctx.el.qq`的类型是number，实际它是string，所以对比就一直是false

![image](https://user-images.githubusercontent.com/25154432/96845827-b3845e80-1483-11eb-9c10-f9c90ce7ff3f.png)

传入配置的时候这里传入数字。

……我之后加个适配吧。我之前以为大家都是直接写 QQ 号来着。

**Comment by YunYouJun** [comment]
好了，已经加上了，可以 `msg.isAt` 了。

**Comment by ZhelinCheng** [comment]
> 好了，已经加上了，可以 `msg.isAt()` 了。

牛逼，够快
