### ISSUE TITLE
当mirai重新启动之后出现的未认证提示。

### ISSUE THREAD

**Issue by ZhelinCheng** [YunYouJun/mirai-ts#17]
在停止mirai并重新登录后，mirai-ts会循环提示`Code 4: Session 未认证(未激活)`

![QQ截图20201027213725](https://user-images.githubusercontent.com/16441850/97309272-c096b880-189c-11eb-9ea5-987fbd0c0592.png)

**Comment by YunYouJun** [comment]
检查一下，mirai-console 与 mirai-ts 中配置的 QQ 号是否一致。

**Comment by YunYouJun** [comment]
重启 el-bot/mirai-ts 即可。中断 mirai 导致 mirai-ts 里验证过的 session 失效了，需要重新验证。

之后考虑做一个自动重新获取验证 session 的兼容处理。

**Comment by ZhelinCheng** [comment]
> 重启 el-bot/mirai-ts 即可。中断 mirai 导致 mirai-ts 里验证过的 session 失效了，需要重新验证。
> 
> 之后考虑做一个自动重新获取验证 session 的兼容处理。

是重启之后解决的，验证提示循环出现感觉不是太友好。
因为我开始以为自动重新处理，大概过了十来分钟左右，发现机器人没反应了上去看，发现一直循环提示。

**Comment by YunYouJun** [comment]
之前做了 Session 失效的自动处理，但是没考虑到 Session 还有未验证的情况，已经加上了。
但是等之后有其他大改动再一起发布版本。

**Comment by YunYouJun** [comment]
Released in `0.7.9`.
