### ISSUE TITLE
机器人断线的处理流程优化

### ISSUE THREAD

**Issue by ZhelinCheng** [YunYouJun/mirai-ts#18]
我机器人掉线以后：
插件一直循环请求：/fetchMessage 这个路由，产生了1.5G的错误日志。
<img width="617" alt="QQ20201117-094338@2x" src="https://user-images.githubusercontent.com/16441850/99329529-685e3f80-28b9-11eb-98af-9fd56801b7d5.png">

**Comment by YunYouJun** [comment]
emm，是把每次的输出内容给存下来了吗？

我能想到的就是设置一个最大重试次数了，先假设最多为 10 次。或者有其他建议方案吗？

**Comment by ZhelinCheng** [comment]
@YunYouJun 我觉得直接触发错误计数会好一些，比如连续触发5次请求错误，甭管什么错误，就停止（或者就改成10分钟后重试），如果有一个监听事件就好了，我就直接邮件通知。

**Comment by YunYouJun** [comment]
其他有一些错误，譬如不是管理员不能禁言之类的，不应该影响到主体，所以暂时只考虑 fetchmessage 失败自动停止。并提供一个配置项，决定重试次数。（还有就是推荐你直接只用 websocket 的主动触发模式，这样就不用去轮询了。）

监听事件是指？ 直接代码应该已经可以自行实现。

**Comment by ZhelinCheng** [comment]
@YunYouJun 可以

**Comment by YunYouJun** [comment]
可通过设置实例化后的 `retries` 来设定 `fetchMessage` 的重试次数，并抛出异常。默认数值为 10。

```js
const mirai = new Mirai(...)
mirai.retries = 20
```

重试次数超额后会抛出异常，可自定捕捉并上报。
