### ISSUE TITLE
mirai.api.memberInfo() 的第三个参数的类型需要是可选类型

### ISSUE THREAD

**Issue by BSG-75** [YunYouJun/mirai-ts#21]
https://github.com/YunYouJun/mirai-ts/blob/a4dd6aaf7236029369808a258834714daab3ced4/src/mirai-api-http/index.ts#L556
否则直接省略/传null之类的会报错qwq

**Comment by YunYouJun** [comment]
Thanks.

Fixed in `mirai-ts@0.8.2`.
