### ISSUE TITLE
src/mirai-api-http/resp.ts 中注释有误

### ISSUE THREAD

**Issue by DGCK81LNN** [YunYouJun/mirai-ts#27]
为什么注释写的是1和2，代码写的是0和1？？
https://github.com/YunYouJun/mirai-ts/blob/66d30f848f1c58240345ac283b07f7b1561b9329/src/mirai-api-http/resp.ts#L20-L24
建议把此文件中的几个`OperationType`类型声明改为`enum`：
```typescript
export enum BotInvitedJoinGroupRequestOperationType {
    accept = 0,
    refuse = 1,
}
```

**Comment by YunYouJun** [comment]
Thanks. Fixed in https://github.com/YunYouJun/mirai-ts/commit/e9907f36e25634b2e7d9662173035cb1f9cd2b52.
Will released in `v1.0.0-alpha.6`.
