### ISSUE TITLE
mirai-api-http 文档链接指向错误

### ISSUE THREAD

**Issue by Discreater** [YunYouJun/mirai-ts#29]
Hi! 文档应该是迁移了，这里的 `EventType.md` 地址应该是 https://github.com/project-mirai/mirai-api-http/blob/master/docs/EventType.md 。另外在 el-bot 的文档中也有这个链接
https://github.com/YunYouJun/mirai-ts/blob/45819b37f7a8d7d9da83f67adfcd792d3f79c05e/src/mirai.ts#L192-L200

**Comment by YunYouJun** [comment]
Thanks. 之后会对其进行修改。

**Comment by YunYouJun** [comment]
Fixed in https://github.com/YunYouJun/mirai-ts/commit/91c2950d334ce61af6364fd0d3e58613715ae376.

Released in `v1.0.0-beta.2`.
