### ISSUE TITLE
`utils/check.ts#match` 函数的实现问题

### ISSUE THREAD

**Issue by Discreater** [YunYouJun/mirai-ts#30]
如果直接调用match的话，会导致后面的配置失效。例如 `@el-bot/plugin-setu` 这个插件，`includes` 中的内容永远不会被匹配到。

https://github.com/YunYouJun/mirai-ts/blob/91c2950d334ce61af6364fd0d3e58613715ae376/src/utils/check.ts#L89-L102

改成或的关系会不会更好，如果re存在且匹配成功则返回正则匹配的结果。如下，个人见解,仅供参考。
```ts
export function match(
  str: string,
  ans: Match
): boolean | RegExpMatchArray | null {
  if (ans.re) {
    const res = re(str, ans.re);
    if (res) return res;
  }
  if (ans.is && is(str, ans.is))
    return true;
  if (ans.includes && includes(str, ans.includes)) {
    return true;
  }
  return false;
}
```

**Comment by YunYouJun** [comment]
`match` 函数只对单一的对象进行判断。当使用 `is` 规则时，不应当再使用 `includes` 的规则。

`setu` 中的 `match` 配置是一个数组，是通过 `forEach` 进行了遍历。

```js
match: [
    {
      is: "不够色",
    },
    {
      includes: ["来", "色图"],
    },
  ],
```

`is` 是否匹配不会影响 `includes` 的匹配。

**Comment by Discreater** [comment]
草，我把 `includes` 拼错了，我说怎么匹配不了，打扰了
