### ISSUE TITLE
能否发送base64的图片

### ISSUE THREAD

**Issue by MemoryDewey** [YunYouJun/mirai-ts#33]
目前看提供的API只支持发送的图片文件，是否可以发送base64url形式的图片

**Comment by YunYouJun** [comment]
这我没试过，我觉得主要应该取决于上游的 mirai-api-http。
https://github.com/project-mirai/mirai-api-http

base64 似乎正在 2.0 的提案征集中。
https://github.com/project-mirai/mirai-api-http/issues/215#issuecomment-774488706

**Comment by YunYouJun** [comment]
先 close 了，如果 2.0 正式了会跟进。
