### ISSUE TITLE
"File" message lost in FriendMessage&GroupMessage

### ISSUE THREAD

**Issue by mice2100** [YunYouJun/mirai-ts#34]
Wont' receive any File message in FriendMessage
onGroupMessage, there is only "Source" in message chain.

**Comment by mice2100** [comment]
Seems an issue in api-http 1.10.0.

**Comment by mice2100** [comment]
After upgrade mirai-api-http to 1.12.0, File can be seen in group message chain. Still lost in FriendMessage

**Comment by YunYouJun** [comment]
Maybe this is related to mirai-api-http. Before that, it did not support manipulating file information.

If you are sure that it is just a problem about mirai-ts, I will try it later.

**Comment by YunYouJun** [comment]
[File | mirai-api-http](https://github.com/project-mirai/mirai-api-http/blob/master/docs/api/MessageType.md#file) can be found in https://github.com/YunYouJun/mirai-ts/blob/5fd736b69766d0a98a28704074dea89bc710f8c5/src/types/message-type.ts#L287-L301.

So I think it has nothing to do with mirai-ts.

By the way, mirai-ts updated file-related api following mah2.x.

Can be found in https://github.com/YunYouJun/mirai-ts/blob/master/src/mirai-api-http/file.ts.
