### ISSUE TITLE
V2.0 MiraiApiHttpSetting interface

### ISSUE THREAD

**Issue by MemoryDewey** [YunYouJun/mirai-ts#37]
2.0的MiraiApiHttpSetting整个interface中的参数都为必传参数，ts编译无法通过，是否可以加入默认配置，并使用?标识attr不为必传参数

**Comment by YunYouJun** [comment]
可以参照 demo 示例使用 as 进行类型断言以解决该情况。

其实比较推荐的方式是直接读取 mirai-api-http setting.yml 文件转 JSON 作为配置传入。

mah 2.0 的配置发生了比较大的变更，我觉得强制提示会对迁移可能更好一些。当然默认值也是可以的，但这样怕用户会忽略掉默认值与 setting.yml 默认值中不一致的地方。

(当然我还不确定那种方式要更为合适，可能有待考虑，如果你有其他更鲜明的理由建议，欢迎提出。)

**Comment by MemoryDewey** [comment]
> 可以参照 demo 示例使用 as 进行类型断言以解决该情况。
> 
> 其实比较推荐的方式是直接读取 mirai-api-http setting.yml 文件转 JSON 作为配置传入。
> 
> mah 2.0 的配置发生了比较大的变更，我觉得强制提示会对迁移可能更好一些。当然默认值也是可以的，但这样怕用户会忽略掉默认值与 setting.yml 默认值中不一致的地方。
> 
> (当然我还不确定那种方式要更为合适，可能有待考虑，如果你有其他更鲜明的理由建议，欢迎提出。)

好的~开发辛苦了
