### ISSUE TITLE
TypeScript 报错 (Cannot find name)

### ISSUE THREAD

**Issue by CL-Jeremy** [YunYouJun/mirai-ts#4]
https://github.com/YunYouJun/mirai-ts/blob/5c35bc80eff923352027f89f970576ae7e098558/types/event-type.d.ts#L53-L57
这里是否应当是 `Contact.Permission`（L167-L168 还有另一处）?

**Comment by YunYouJun** [comment]
Yes. Thanks. Fixed. Please install mirai-ts@0.3.2.
