### ISSUE TITLE
API 和最新的 mirai-api-http 相比有缺失

### ISSUE THREAD

**Issue by CaoMeiYouRen** [YunYouJun/mirai-ts#42]
和 [mirai-api-http](https://github.com/project-mirai/mirai-api-http/blob/master/docs/api/API.md) 相比，少了一些接口的定义。
比如  获取Bot资料 、获取好友资料、获取群成员资料 等

____

### 获取群设置

使用此方法获取群设置

```
[GET] /groupConfig
```

**本接口为[GET]请求, 参数格式为URL参数**

通用接口定义: [获取群设置](../api/API.md#获取群设置)

### 修改群设置

使用此方法修改群设置（需要有相关限权）

```
[POST] /groupConfig
```

**本接口为[POST]请求, 参数格式为`application/json`**

通用接口定义: [修改群设置](../api/API.md#修改群设置)

### 获取群员设置

使用此方法获取群员设置

```
[GET] /memberInfo
```

**本接口为[GET]请求, 参数格式为URL参数**

**Comment by Samarium150** [comment]
确实，没有找到如何获取bot资料。但可以用`axios`直接发请求临时用一用。
```typescript
interface Profile {
    nickname: string;
    email: string;
    age: number;
    level: number;
    sign: string;
    sex: string;
}
async function main(): Promise<void> {
    const profile = (await mirai.axios.get("/botProfile")).data as Profile;
}
```

**Comment by CaoMeiYouRen** [comment]
> 确实，没有找到如何获取bot资料。但可以用`axios`直接发请求临时用一用。
> 
> ```ts
> interface Profile {
>     nickname: string;
>     email: string;
>     age: number;
>     level: number;
>     sign: string;
>     sex: string;
> }
> async function main(): Promise<void> {
>     const profile = (await mirai.axios.get("/botProfile")).data as Profile;
> }
> ```

嗯，我了解。主要是我看了下少了好几个接口的定义，估计是版本更新的缘故

**Comment by YunYouJun** [comment]
`groupConfig/memberInfo` 等 API 是有的，可以在 https://www.yunyoujun.cn/mirai-ts/ 进行搜索。

> https://www.yunyoujun.cn/mirai-ts/classes/MiraiApiHttp.html#groupConfig

`botProfile` 应该是新增的 API，将会尽快添加。

**Comment by YunYouJun** [comment]
Release in `v2.1.1`.

我将关闭该 Issue，如果仍然有问题，欢迎随时反馈。
