### ISSUE TITLE
建议使用 private 修饰符修饰部分字段

### ISSUE THREAD

**Issue by CaoMeiYouRen** [YunYouJun/mirai-ts#43]
我注意到在 Mirai 、MiraiApiHttp 等类中有部分字段应该是私有的、不对外开放的，可以考虑用 private 修饰符修饰部分字段

**Comment by YunYouJun** [comment]
Thanks. 能否举例？或者是否愿意直接提交 PR 呢？

**Comment by CaoMeiYouRen** [comment]
> Thanks. 能否举例？或者是否愿意直接提交 PR 呢？

类似于这样，"_"开头的应该都是私有的吧。这样在编辑器里就不会提示私有字段或方法。

```ts
 /**
   * 构建 WebSocket 通道
   * @param type
   */
  private _buildWsChannel<T extends "message" | "event" | "all">(
    type: T,
    callback: WsCallbackMap[T]
  ) {}
```
我之后有空的话可以帮忙改下，但我不确定你是怎么设计的，哪些是要公开的，我还要再看下
