### ISSUE TITLE
bot  mirai.api.sendGroupMessage 能不能加个代理配置。。。

### ISSUE THREAD

**Issue by loneyclown** [YunYouJun/mirai-ts#47]
有时候发的图片在墙外，不走代理可能发不出去，要自己转base又太麻烦了。
![image](https://user-images.githubusercontent.com/29278254/145507588-37c2457d-b77c-4169-97e7-1591bf7d545d.png)
然后我这样发请求，好像拿到的sessionKey是错的。。。
![image](https://user-images.githubusercontent.com/29278254/145507524-0ea92227-31ad-40fc-93ee-ab108cb60115.png)
那么mirai.api下的方法能不能有个配置axios的口子呢。。。

**Comment by YunYouJun** [comment]
axios 是 mirai 初始化后的一个子项，可以直接通过 mirai.axios 进行调用，其他配置与 axios 实例相同。

![image](https://user-images.githubusercontent.com/25154432/145578647-344e1b21-6548-40f7-b0d7-a3dc49a2d372.png)
