### ISSUE TITLE
mirai-api-http 更新之后，messageFromId 方法需要传额外的参数，大佬能更新一下版本吗？

### ISSUE THREAD

**Issue by GeraltX** [YunYouJun/mirai-ts#51]

**Comment by YunYouJun** [comment]
Will fix it asap.

**Comment by YunYouJun** [comment]
![image](https://user-images.githubusercontent.com/25154432/192677463-e62c14ed-015d-409e-bd33-4abec322f46b.png)

target 参数？

**Comment by GeraltX** [comment]
![image](https://user-images.githubusercontent.com/11661132/192682484-b01fb18f-735e-4bb7-8aba-d935548b58c2.png)
我昨天升级了 mirai-api-http 到 2.6.2，获取消息就返回了这个
`{"code":500,"msg":"An unknown field for index -3"}` 
然后看了下它的更新日志，它说加了新的参数，我也不清楚。。

**Comment by GeraltX** [comment]
![image](https://user-images.githubusercontent.com/11661132/193207291-81273bc7-92da-4578-b198-ce648d860a98.png)
<https://github.com/project-mirai/mirai-api-http/commit/8ba96b5dd7362ef83bde9f210d43d319319bc896>
翻了一下更新，应该就是这个 target 参数了

**Comment by GeraltX** [comment]
不好意思又来打扰了。
上次报完 issue 之后，就没继续跟进了。最近更新了新版本之后发现还是不行，去 mirai-api-http 那边看了下，好像是它改了参数名，麻烦大佬跟进一下~
[#625](https://github.com/project-mirai/mirai-api-http/issues/625#issuecomment-1345809137)
![image](https://user-images.githubusercontent.com/11661132/208338603-0c6e8d82-0df9-447b-af7c-02ab242c3987.png)
