### ISSUE TITLE
MessageType怎么引用？

### ISSUE THREAD

**Issue by bincooo** [YunYouJun/mirai-ts#57]
import { Mirai, MessageType } from 'mirai-ts'
import type { MiraiApiHttpSetting } from 'mirai-ts'
import { config } from 'src/config'
import { BaseMessageHandler, MessageHandler } from 'src/types'

  console.log(MessageType)

----
貌似取不到GroupMessage
对nodejs不熟悉。。。

**Comment by YunYouJun** [comment]
`MessageType.GroupMessage`
