### ISSUE TITLE
请问使用 MAH 2.10.0 时 ws 报错

### ISSUE THREAD

**Issue by gebederry** [YunYouJun/mirai-ts#60]
### Describe the bug

不知佬目前是否还维护着这个项目，试着提个 issue 吧..
[MAH](https://github.com/project-mirai/mirai-api-http) 近期发布的 [2.10.0](https://github.com/project-mirai/mirai-api-http/releases/tag/v2.10.0) 适配了 [mirai core 2.16.0](https://github.com/mamoe/mirai/releases/tag/v2.16.0) 的一些新功能，比如终于支持了短视频发送。有需求所以将 MAH 升级到了 2.10.0，结果与 mirai-ts 对接时 ws 报错。

![MobaXterm_MDiZHph0QE](https://github.com/YunYouJun/mirai-ts/assets/3938353/59527882-4859-4bb5-8760-0a200ffc7322)

不确定是不是 mirai-ts 这边的问题，请佬看一下.... 🙏🏾

### Reproduction

使用 MAH 2.10.0

### System Info

```Shell
System:
    OS: Linux 4.11 CentOS Linux 7 (Core)
    CPU: (2) x64 QEMU Virtual CPU version (cpu64-rhel6)
    Memory: 455.55 MB / 1.97 GB
    Container: Yes
    Shell: 4.2.46 - /bin/bash
  Binaries:
    Node: 20.6.1 - ~/.nvm/versions/node/v20.6.1/bin/node
    npm: 10.1.0 - ~/.nvm/versions/node/v20.6.1/bin/npm
    pnpm: 8.7.5 - ~/.nvm/versions/node/v20.6.1/bin/pnpm
    bun: 1.0.0 - ~/.bun/bin/bun
  Browsers:
    Chrome: 116.0.5845.179
```

### Used Package Manager

npm

### Validations

- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by YunYouJun** [comment]
跑了半天，发现甚至账号都登不上了（

**Comment by gebederry** [comment]
> 跑了半天，发现甚至账号都登不上了（

另有一台服务器的 mirai 已登录了 QQ，刚刚发到您的电邮了 [me@yunyoujun.cn](mailto:me@yunyoujun.cn)
🙏

**Comment by OOO-li-ooo** [comment]
貌似是WebSocket连接的**响应头**里的`Sec-WebSocket-Extensions`是`frame-log`导致的
<img width="403" alt="image" src="https://github.com/YunYouJun/mirai-ts/assets/60606236/70721e99-85b7-46a5-b42d-e1f677f5c269">

而ws库里的代码貌似只能处理extension的第一个是`permessage-deflate`的情况
```js
if (
  extensionNames.length !== 1 ||
  extensionNames[0] !== PerMessageDeflate.extensionName
) {
  const message = 'Server indicated an extension that was not requested';
  abortHandshake(websocket, socket, message);
  return;
}

try {
  perMessageDeflate.accept(extensions[PerMessageDeflate.extensionName]);
} catch (err) {
  const message = 'Invalid Sec-WebSocket-Extensions header';
  abortHandshake(websocket, socket, message);
  return;
}
```
