### ISSUE TITLE
前天的修改之后又找不到 export 了

### ISSUE THREAD

**Issue by CL-Jeremy** [YunYouJun/mirai-ts#8]
刚刚更新“生产环境”的机器人，才发现 https://github.com/YunYouJun/mirai-ts/commit/2ce9e92143aec3885274bb9c3caa2dd4bc8485ea 的修改是不是在使用的时候需要改动 `import` 的语法？ `import Mirai from 'mirai-ts';` 会报错，现在只有 `require('mirai-ts')` 可用……

**Comment by YunYouJun** [comment]
`import Mirai from "mirai-ts"` 可以啊，我自己正用着呢。

版本是？当前最新版本是 `v0.4.5`。

**Comment by YunYouJun** [comment]
https://github.com/YunYouJun/mirai-ts/commit/2ce9e92143aec3885274bb9c3caa2dd4bc8485ea 这里的修改是为了适配 nodejs，以便使用 `require("mirai-ts")` 而非 `require("mirai-ts").default`。

应该不会对 `import Mirai from 'mirai-ts'` 的语法产生影响。

**Comment by CL-Jeremy** [comment]
肯定是最新版本的，但是我这里报错
```ts
            this.bot = new mirai_ts_1.default({
                       ^

TypeError: mirai_ts_1.default is not a constructor
```

**Comment by YunYouJun** [comment]
能否提供一下原项目此处的代码链接？

**Comment by CL-Jeremy** [comment]
> [2ce9e92](https://github.com/YunYouJun/mirai-ts/commit/2ce9e92143aec3885274bb9c3caa2dd4bc8485ea) 这里的修改是为了适配 nodejs，以便使用 `require("mirai-ts")` 而非 `require("mirai-ts").default`。
> 
> 应该不会对 `import Mirai from 'mirai-ts'` 的语法产生影响。

我知道，但是我不是很明白：
```diff
-   module.exports = Mirai;
-   module.exports.default = Mirai;
-   module.exports.Mirai = Mirai;
+   exports = module.exports = Mirai;
```
这两个等价吗？

**Comment by CL-Jeremy** [comment]
> 能否提供一下原项目此处的代码链接？

https://github.com/CL-Jeremy/mirai-twitter-bot/blob/master/src/mirai.ts

**Comment by YunYouJun** [comment]
> 这两个等价吗？

exports 是对 module.exports 的引用，只在原生的 nodejs 中我们需要用到 `module.exports`。因为 `require()` 返回的是 `module.exports`，而 TypeScript 可以使用 ES6+ 的 import 语法，直接调用 exports 即可。

本质上是：

```js
module.exports = Mirai
exports = module.exports
```

---

> https://github.com/CL-Jeremy/mirai-twitter-bot/blob/master/src/mirai.ts

我尝试 clone 了您的项目，构建时并没有发现报错提示。重新安装下 node_modules ?

**Comment by YunYouJun** [comment]
也可能与 node 版本有关，我当前使用的是 nodejs LTS 版本（12.18.3）。

**Comment by CL-Jeremy** [comment]
这种诸如 `import * as A from 'a';` 与 `import A from 'a';` 的差异在构建时不会体现，可以尝试执行一下 `node dist/main.js config.json.example`。

**Comment by CL-Jeremy** [comment]
> 也可能与 node 版本有关，我当前使用的是 nodejs LTS 版本（12.18.3）。

服务器上同为 12.18.3（本机上是 14.x）

**Comment by YunYouJun** [comment]
https://github.com/YunYouJun/mirai-ts/commit/5d936932508e0e14529229c1c5f5ef386cc2341b 已同时导出 default 以修复该问题。
已 release v0.4.6。我测试已可以正常运行。
如果没问题的话，可以关闭该 ISSUE。

**Comment by CL-Jeremy** [comment]
是不是因为我 tsconfig.json 的设置呢？因为如上面我报错的信息所示，我生成的 JS 在创建时肯定还是在调用 `require ('mirai-ts').default`，是否这种情况下必须定义 `module.exports.default` 呢？

**Comment by CL-Jeremy** [comment]
好的，多谢！

**Comment by YunYouJun** [comment]
> 是不是因为我 tsconfig.json 的设置呢？因为如上面我报错的信息所示，我生成的 JS 在创建时肯定还是在调用 require ('mirai-ts').default，是否这种情况下必须定义 module.exports.default 呢？

发现 TypeScript 构建后总是使用 .default，而我之所以可以正常使用，是因为我开发的 el-bot 更接近于一个库，导出时会自动加上 `__importDefault()` 的函数，来适配是否使用 default。

而本质上，你也可以考虑使用导出一个主入口文件的方式来使用，而非直接执行编译后的部分 js 文件。当然这也并非必要的。

主动适配 module.exports.default 显然是更好的方式。
